### ISSUE TITLE
menu collapsed

### ISSUE THREAD

**Issue by yukulele** [numixproject/numix-gtk-theme-dark#1]
- some applications (mousepad, engrampa, terminal-emulator, ...) menu look collapsed
- Nautilus is look totally flat and collapsed

I'm on Ubuntu 18.04 + xfce 4.12
![capture d ecran_2018-07-17_15-49-42](https://user-images.githubusercontent.com/347244/42821923-fca3481a-89d9-11e8-998d-5a4686216d44.png)

**Comment by Foggalong** [comment]
As mentioned in the README this theme only supports up to GTK 3.14, whereas the version of Nautilus in 18.04 uses GTK 3.22 and above. For now these themes are just here so our GTK team can assess how easy it would be to update them so they're on par with our main GTK theme.
